# Generated by Django 5.1.2 on 2025-02-19 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_username_alter_user_membership_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
